name: test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: verification
      

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-coverage
    - name: tests running 
      run: |
        coverage run -m pytest tests/test_fibonacci.py
        coverage report
        token: ${{ secrets.GIT_TOKEN }}