name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest
    - name: Build distribution packages
      run: |
        python setup.py sdist bdist_wheel
      if: success()
    - name: Publish distribution packages
      uses: actions/upload-artifact@v2
      with:
        name: dist-packages
        path: dist/
      if: success()