name: Coverage

on:
  pull_request:
    branches: [dev]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and coverage
        run: |
          pytest --cov=./
          coverage html
          echo "::set-output name=coverage_path::$(pwd)/htmlcov/index.html"

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: coverage-report
          path: ${{ github.workspace }}/htmlcov

      - name: Comment on pull request
        uses: actions/github-script@v4
        if: always()
        with:
          script: |
            var prNumber = context.payload.pull_request.number;
            var coveragePath = process.env.coverage_path;
            var commentBody = "Code coverage report:\n\n";
            commentBody += `![coverage report](${coveragePath})`;
            github.issues.createComment({
              issue_number: prNumber,
              body: commentBody
            })
        env:
          coverage_path: ${{ steps.coverage.outputs.coverage_path }}
