name: coverage

on:
  pull_request:
    branches: 
      - dev

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
    - name: Tests and report
      run: |
        pytest --cov=. --cov-report=xml
    - name: Create report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.xml
